version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'YourStrong!Passw0rd'
    ports:
      - '1433:1433'
    networks:
      - mssql-net

networks:
  mssql-net:
    name: mssql-net
